<?php /* Smarty version Smarty-3.1.19, created on 2014-10-28 09:51:10
         compiled from "/mnt/hgfs/Sites/buildcommand/App/Views/site/terms.tpl" */ ?>
<?php /*%%SmartyHeaderCode:240831719542b4ee2cdcf34-37739521%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    '1f365400f8c3365cc92421f16d00194caecba1c0' => 
    array (
      0 => '/mnt/hgfs/Sites/buildcommand/App/Views/site/terms.tpl',
      1 => 1414509466,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '240831719542b4ee2cdcf34-37739521',
  'function' => 
  array (
  ),
  'version' => 'Smarty-3.1.19',
  'unifunc' => 'content_542b4ee2cf0b36_38228656',
  'variables' => 
  array (
    'is_micro' => 0,
  ),
  'has_nocache_code' => false,
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_542b4ee2cf0b36_38228656')) {function content_542b4ee2cf0b36_38228656($_smarty_tpl) {?><?php if (!$_smarty_tpl->tpl_vars['is_micro']->value) {?>
		<h1>Terms &amp; Conditions</h1>
<?php }?>
<div id="public">	
These Terms of Use govern your use of the BuildCommand.com website (“our Site”), which is owned and operated by BuildCommand, LLC (“BuildCommand” or “we”).  These Terms of Use also govern your participation in any Sponsored Activity (as defined below).<br />
<br />
1.	Acceptance.  By using or visiting our Site or participating in any Sponsored Activity you confirm your agreement to:  (a) these Terms of Use, (b) BuildCommand’s Privacy Policy, found at http://www.BuildCommand.com/privacy, and (c) Other Agreements .  Build Command’s Privacy Policy is  incorporated by reference herein.  If you do not agree to any of these Terms of Use or the Privacy Policy, please do not use our Site or participate in any Sponsored Activity.
Although we may attempt to notify you when major changes are made to these Terms of Use, you should periodically review the most current version at http://www.BuildCommand.com/Terms_Of_Use.  Build Command may, in its sole discretion, modify or revise these Terms of Use and policies at any time, and you agree to be bound by such modifications or revisions.  Nothing in these Terms of Use shall be deemed to confer any third party rights or benefits.<br />
<br />
2.	Sponsored Activity.  “Sponsored Activity” or “Sponsored Activities” means any and all online and offline activities sponsored by BuildCommand, including, without limitation, (a) visiting and viewing our Site and any other websites operated by BuildCommand; (b) submission of any Project Proposal (as defined below); (c) review of any Project Proposal; and (d) participation in any forum, message board, bulletin board, internal messaging system, or social media site or program sponsored by BuildCommand. <br />
<br />
3.	Your Account.  To access our Site, make purchases of products or services, or participate in any Sponsored Activity you may be asked to (a) provide certain registration details or other information; (b) to establish a user account specific to you (“your Account”).  To create your Account, you must qualify under and agree to the conditions set forth below: 
<ul>
	<li>You are either 18 years old or older or the age of legal consent in your jurisdiction, whichever is older.  We expressly reserve the right (but do not have the obligation) to request proof of age, at any time.</li>
	<li>All information that you provide in your registration form for the purposes of establishing your Account is true and correct and you will promptly notify us of any changes to such information.</li>
	<li>You acknowledge that in establishing your Account you have provided us with certain personal information about you.  While we normally keep this information confidential, you agree that it may be necessary, from time to time, to disclose certain personal information to third parties and you consent to all such disclosures.  Please see our Privacy Policy for further information.</li>
	<li>Your Account is for your sole use only and must not be used by any third party.  You shall not allow any third party to use your Account, password, log-in or user ID to access or use the Site to arrange, enter, and/or participate in any Sponsored Activity, or for any other purposes.  We take no responsibility for any third party access to your Account.</li>
	<li>You have verified and determined that your use of the Site does not violate any law or regulation in any jurisdiction that applies to you.  It is your sole responsibility to ensure that this is the case.</li>
	<li>You fully understand the methods, rules and procedures of the Site, and your use of the Site and participation in any Sponsored Activity will always comply fully with this Agreement, the Privacy Policy and the Project Proposal Submission Agreement.</li>
	<li>You will not engage in any conduct that injures or may injure the business, reputation or goodwill of BuildCommand.</li>
	<li>You possess the legal authority to enter into this Agreement including the authority to accept all of these Terms of Use.</li>
	<li>You shall not infringe or encroach upon BuildCommand’s or any third party’s personal, contractual or proprietary rights, including, without limitation, patents, trademarks, copyrights, rights of privacy or publicity or trade secrets.</li> 
	<li>You are physically located in a U.S. state , or a jurisdiction located outside the United States, in which participation in Site or Sponsored Activities are not prohibited by the law of that state or jurisdiction.</li>
	<li>You will not use the Site or any Sponsored Activity for fraudulent or otherwise illegal purposes; should you learn that any user is using the Site or any Sponsored Activity for fraudulent or otherwise illegal purposes, you will immediately notify us in writing.</li>
	<li>You understand that we may monitor your Internet access location, without creating an obligation to do so, and may use techniques which are intended to block or restrict access from a jurisdiction in which participation in the Site or any Sponsored Activity is illegal or restricted.</li>
	<li>You will not mask your identify in any way, including without limitation, IP masking by accessing the Site or any Sponsored Activity over any type of proxy server, through IP masking software or the like.</li>
</ul>
<br />
4.	Use of this Site.  BuildCommand hereby grants you permission to access and use our Site and to engage in Sponsored Activities subject to these Terms of Use, and provided that you agree:
<ul>
	<li>not to alter or modify any part of our Site;</li>
	<li>not to engage in the sale of access to our Site or any Project Proposal on our Site;</li>
	<li>not to engage in the sale of advertising, sponsorships, or promotions placed on or within our Site or any Project Proposal;</li>
	<li>not to engage in the sale of advertising, sponsorships, or promotions on any page of an ad-enabled blog or website containing a Project Proposal delivered via our Site;</li>
	<li>not to circumvent, disable or otherwise interfere with security-related features of our Site or any Sponsored Activity or features that prevent or restrict use or copying of any Project Proposal or enforce limitations on use of our Site or any Sponsored Activity or a Project Proposal therein;</li>
	<li>not to use or launch any automated system, including without limitation, “robots,” “spiders,” or “offline readers,” that accesses our Site in a manner that sends more request messages to the BuildCommand servers in a given period of time than a human can reasonably produce in the same period by using a conventional on-line web browser;</li>
	<li>not to collect or harvest any personally identifiable information, including account names, from our Site, nor to use the communication systems provided by our Site or any Sponsored Activity (e.g., email, or comments or other posts in a forum or on a message board, internal messaging system or bulletin board) for any commercial solicitation purpose; and</li>
	<li>not to solicit, for commercial purposes, any users of our Site or any Sponsored Activity, including with respect to their Project Proposal.</li> 
</ul>
Notwithstanding the foregoing, BuildCommand grants the operators of public search engines permission to use spiders to copy materials from the Site for the sole purpose of and solely to the extent necessary for creating publicly available searchable indices of the Project Proposal, but not caches or archives of such Project Proposal .  BuildCommand reserves the right to revoke these exceptions either generally or in specific cases.  In your use of our Site or participation in any Sponsored Activity, you will comply with all applicable laws.<br />
<br />
BuildCommand reserves the right to discontinue any aspect of our Site or any Sponsored Activity at any time.<br />
<br />
5.	Project Proposal.  “Project Proposal” means all building plans, schedules, works of authorship, and other materials and intellectual property developed or provided by you, BuildCommand or its licensors, users of our Site or other websites operated by BuildCommand, and any participants in any Sponsored Activity, including, without limitation, text, graphics, illustrations, still photography, slides, audiovisual combinations, animations, sounds, music, and motion videography.  Project Proposal shall also include any Projects (as defined in the Project Proposal Submission Agreement), and any HTML code or other code developed or provided by BuildCommand to be used in connection our Site, other websites operated by BuildCommand, or any Sponsored Activity.<br />
<br />
(a)	Restrictions.	You may not post, send, submit, publish, or transmit in connection with our Site or any Sponsored Activity any Project Proposal that:<br />
<ul>
	<li>you do not have the right to post, including confidential or proprietary content, material or personal or financial information of any third party;</li>
	<li>is false, inaccurate or misleading</li>
	<li>advocates illegal activity or discusses an intent to commit an illegal act;</li>
	<li>is vulgar, obscene, pornographic, sexually-oriented, indecent, or otherwise in violation of any laws;</li>
	<li>does not pertain directly to our Site or the applicable Sponsored Activity;</li>
	<li>threatens or abuses others, libels, defames, invades privacy, stalks, or is racist, abusive, harassing, threatening or offensive;</li>
	<li>seeks to exploit or harm children by exposing them to inappropriate Project Proposal asking for personally identifiable details or otherwise;</li>
	<li>infringes any intellectual property or other right of any entity or person, including violating anyone’s patents, trade secrets, copyrights or trademarks or their rights of publicity;</li>
	<li>violates any law or may be considered to violate any law;</li>
	<li>impersonates or misrepresents your connection to any other entity or person or otherwise manipulates headers or identifiers to disguise the origin of the content, material or information;</li>
	<li>includes programs which contain viruses, worms and/or Trojan horses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications;</li>
	<li>disrupts the normal flow of dialogue, causes a screen to scroll faster than other users are able to type, or otherwise act in a way which affects the ability of other people to engage in real time activities our Site;</li>
	<li>disobeys any policy or regulations established from time to time regarding use of our Site or participation in any Sponsored Activities;</li>
	<li>contains hyperlinks to other websites that contain content that falls within the descriptions set forth above;</li>
</ul>
	or<br />
<ul>
	<li>advertises, promotes, or solicits the donation, sale or purchase of non-BuildCommand products or services, the distribution of non-BuildCommand related coupons, eBay postings etc, are prohibited;</li>
	<li>advertises, promotes or solicits participation in a multi-level marketing or pyramid scheme; or</li>
	<li>advertises, promotes, or solicits other users to join or become members of any commercial online service or other organization.</li>

BuildCommand reserves the right to remove any posting, discussion, message or thread containing any of the Project Proposal prohibited above. <br />
<br />
(b)	Your use of a Project Proposal.  In addition to the general restrictions above, the following restrictions and conditions apply specifically to your use of Project Proposal of others.  Project Proposals are provided to you AS IS and without any warranty. You may access Project Proposals for your information and use solely as intended through the provided functionality of our Site and any Sponsored Activity and as permitted under these Terms of Use.  You shall not download any Project Proposal unless you see a “download” or similar link displayed by BuildCommand in connection with that Project Proposal . You shall not copy, reproduce, distribute, transmit, broadcast, display, sell, license, or otherwise exploit any Project Proposal for any other purposes without the prior written consent of BuildCommand or the respective creators or licensors of the Project Proposal.  BuildCommand and its licensors reserve all rights not expressly granted in and to the Project Proposal.<br />
You understand that when using our Site and participating in any Sponsored Activity, you will be exposed to Project Proposals from a variety of sources, and that BuildCommand is not responsible for the accuracy, usefulness, safety, or intellectual property rights of or relating to such Project Proposals. You further understand and acknowledge that you may be exposed to a Project Proposal(s) that is inaccurate, offensive, indecent, or objectionable, and you agree to waive, and hereby do waive, any legal or equitable rights or remedies you have or may have against BuildCommand with respect thereto, and, to the extent permitted by applicable law, agree to indemnify and hold harmless BuildCommand, its owners, operators, affiliates, licensors, and licensees to the fullest extent allowed by law regarding all matters related to your use of any Project Proposal.<br />
<br />
(c)	Your Submissions .  Although BuildCommand does not claim ownership of all Project Proposals that you post or submit, by posting or submitting a Project Proposal to our Site or in connection with any Sponsored Activity, you automatically grant, and you represent and warrant that you have the right to grant, to BuildCommand an irrevocable, perpetual, non-exclusive, fully paid, worldwide right and license to use, copy, perform, display, and distribute each such Project Proposal and to prepare derivative works of, or incorporate into other works, each such Project Proposal and to grant and authorize sublicenses of the foregoing.  Furthermore, by posting or submitting to our Site or in connection with any Sponsored Activity, you automatically grant BuildCommand all rights necessary to prohibit any subsequent aggregation, display, copying, duplication, reproduction, or exploitation of such Project Proposal by any party for any purpose. <br />
<br />
6.		Payments.  All payments to BuildCommand to open your Account, participate in other Sponsored Activities, or purchase other goods or services must be made using PayPal , credit card or other means of payment that we may approve from time to time.  All payments to BuildCommand must be made from a payment source on which you are legally authorized to use for such payments. All payments to BuildCommand are not refundable, for any reason.<br />
You agree that BuildCommand is not liable for any loss caused by any unauthorized use of your PayPal Account, your credit card or any other method of payment by a third party in connection with our Site or any Sponsored Activity. You waive your right to dispute any payment made into your Account and you will personally bear all costs.
Any attempt to defraud our Site through the use of PayPal, credit cards or other methods of payment, or any failure by you to honor charges or requests for payment will result in immediate termination of your Account, forfeiture of any prizes which you may have been awarded, and civil and/or criminal prosecution.<br />
In the case of suspected or fraudulent payment, including use of stolen PayPal credentials or credit card information, by anyone, or any other fraudulent activity, we reserve the right to block your Account. We shall be entitled to inform any relevant authorities or entities (including credit reference agencies) of any payment fraud or other unlawful activity, and may employ collection services to recover payments.  We reserve the right to run credit checks on any user on the basis of the information provided to us on registration. <br />
BuildCommand may use third-party electronic payment processors and/or financial institutions (“ESPs”) to process financial transactions.  You irrevocably authorize us, as necessary, to instruct such ESPs to handle such transactions and you irrevocably agree that BuildCommand may give such instructions on your behalf in accordance with your requests as submitted with your order. You agree to be bound by the terms and conditions of use of each applicable ESP, and in the event or conflict between these Terms of Use and the ESP’s terms and conditions then these Terms of Use shall govern. <br />
<br />
7.		Promotions.  BuildCommand offered Sponsored Activities comprised of sweepstakes, contests or other promotions, which may be governed by a separate set of rules that describe the sweepstakes, contest or promotion and may have eligibility requirements, such as certain age or geographic area restrictions. It is your responsibility to read those rules to determine whether or not your participation, registration or entry will be valid or restricted, and to determine any requirements of You in connection with the applicable sweepstakes, contest or promotion. <br />
<br />
8.		Risk of Loss.  All items purchased from BuildCommand are made pursuant to a shipment contract.  This means that the risk of loss and title for such items pass to you upon our delivery to the carrier.<br />
<br />
9.		Intellectual Property Rights.  Unless otherwise noted, all Project Proposal on our Site or furnished in connection with any Sponsored Activity is subject to the copyright, trademark, trade dress and other intellectual property rights held by BuildCommand or its affiliates or by third parties who have licensed their Project Proposal and rights to BuildCommand.  All such rights are protected by U.S. and international copyright and trademark laws.  BuildCommand, its affiliate and licensors expressly reserve all intellectual property rights in all Project Proposals which appear on our Site or is furnished in connection with any Sponsored Activity.  Access to our Site does not confer and shall not be deemed as conferring upon anyone any license under any of BuildCommand’s or any third party’s intellectual property rights.<br />
No trademark or service mark license is granted in connection with the Project Proposal contained on this website, and access to our Site does not authorize anyone to use any name, logo or mark in any manner.  References on our Site to any names, marks, products or services of third parties or hypertext links to third party sites or information are provided solely as a convenience to you and do not in any way constitute or imply BuildCommand’s endorsement, sponsorship or recommendation of such third party, or its information, products or services.<br />
<br />
11.	Security.  You are prohibited from using any services or facilities provided in connection with our Site to compromise security or tamper with system resources and/or accounts.  The use or distribution of tools designed for compromising security (e.g., password guessing programs, cracking tools or network probing tools) is strictly prohibited.  If you become involved in any violation of system security, BuildCommand reserves the right to release your personal and account information to system administrators at other sites in order to assist them in resolving security incidents.  BuildCommand reserves the right to fully cooperate with any law enforcement authorities or court order requesting or directing BuildCommand to disclose the identity of anyone posting any e-mail messages, or publishing or otherwise making available any materials that are believed to violate these Terms of Use.  BY ACCEPTING THIS AGREEMENT YOU WAIVE AND AGREE TO HOLD HARMLESS BUILDCOMMAND FROM ANY CLAIMS RESULTING FROM ANY ACTION TAKEN BY BUILDCOMMAND DURING OR AS A RESULT OF ITS INVESTIGATIONS AND/OR FROM ANY ACTIONS TAKEN AS A CONSEQUENCE OF INVESTIGATIONS BY EITHER BUILDCOMMAND OR LAW ENFORCEMENT AUTHORITIES.<br />
<br />
12.	Digital Millennium Copyright Act.  If you are a copyright owner or an agent thereof and believe that any Project Proposal infringes upon your copyrights, you may submit a notification pursuant to the Digital Millennium Copyright Act (“DMCA”) by providing our Copyright Agent with the following information in writing (see 17 U.S.C §512(c)(3) for further detail): <br />
<ul>
	<li>a physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;</li>
	<li>identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works are covered by a single notification, a representative list of such works;</li>
	<li>identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled and information reasonably sufficient to permit BuildCommand to locate the material; </li>
	<li>information reasonably sufficient to permit BuildCommand to contact you, such as an address, telephone number, and, if available, an electronic mail;</li>
	<li>a statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and</li>
	<li>a statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</li>
</ul>

BuildCommand’s designated Copyright Agent  to receive notifications of claimed infringement is BuildCommand, Attn: Copyright Agent, PO Box ####, Fruitland, ID 83619; email: copyright@BuildCommand.com . For clarity, only DMCA notices should go to the Copyright Agent; any other feedback, comments, requests for technical support, and other communications should be directed to BuildCommand through support@BuildCommand.com.  You acknowledge that if you fail to comply with all of the requirements of this Section 12, your DMCA notice may not be valid.<br />
<br />
Counter-Notice. If you believe that your content that was removed (or to which access was disabled) is not infringing, or that you have the authorization from the copyright owner, the copyright owner’s agent, or pursuant to the law, to post and use the material in your content, you may send a counter-notice containing the following information to the Copyright Agent: <br />
<ul>
	<li>your physical or electronic signature;</li>
	<li>identification of the content that has been removed or to which access has been disabled and the location at which the content appeared before it was removed or disabled;</li>
	<li>a statement that you have a good faith belief that the content was removed or disabled as a result of mistake or a misidentification of the content; and</li>
	<li>your name, address, telephone number, and e-mail address, a statement that you consent to the jurisdiction of the federal court in Boise, Idaho, and a statement that you will accept service of process from the person who provided notification of the alleged infringement.</li>
</ul>
If a counter-notice is received by the Copyright Agent, BuildCommand may send a copy of the counter-notice to the original complaining party informing that person that it may replace the removed content or cease disabling it in ten (10) business days. Unless the copyright owner files an action seeking a court order against the content provider, member or user, the removed content may be replaced, or access to it restored, in ten (10) to fourteen (14) business days or more after receipt of the counter-notice, at BuildCommand’s sole discretion.<br />
<br />
13.	Warranty Disclaimer.  YOU AGREE THAT YOUR USE OF OUR SITE AND YOUR PARTICIPATION IN ANY SPONSORED ACTIVITY SHALL BE AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMITTED BY LAW, BUILDCOMMAND, ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH OUR SITE AND YOUR PARTICIPATION IN ANY SPONSORED ACTIVITY.  BUILDCOMMAND MAKES NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF OUR SITE’S CONTENT OR THE CONTENT OF ANY SITES LINKED TO OUR SITE AND ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY (A) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT, (B) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF OUR SITE OR YOUR PARTICIPATION IN ANY SPONSORED ACTIVITY , (C) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR PAYMENT ACCOUNT INFORMATION STORED THEREIN, (D) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM OUR SITE OR SERVERS, (E) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH OUR SITE OR SERVERS BY ANY THIRD PARTY, AND/OR (F) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA OUR SITE OR ANY SPONSORED ACTIVITY.   BUILDCOMMAND DOES NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH OUR SITE OR ANY SPONSORED ACTIVITY OR ANY HYPERLINKED SERVICES OR FEATURED IN ANY BANNER OR OTHER ADVERTISING, AND BUILDCOMMAND WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND THIRD PARTY PROVIDERS OF PRODUCTS OR SERVICES. AS WITH THE PURCHASE OF A PRODUCT OR SERVICE THROUGH ANY MEDIUM OR IN ANY ENVIRONMENT, YOU SHOULD USE YOUR BEST JUDGMENT AND EXERCISE CAUTION WHERE APPROPRIATE.<br />
<br />
14.	Limitation of Liability.  IN NO EVENT SHALL BUILDCOMMAND, ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS, BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES WHATSOEVER RESULTING FROM ANY (A) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT, (B) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF OUR SITE OR YOUR PARTICIPATION IN ANY SPONSORED ACTIVITY, (C) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR  PAYMENT ACCOUNT INFORMATION  STORED THEREIN, (D) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM OUR SITE OR SERVERS, (E) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE, WHICH MAY BE TRANSMITTED TO OR THROUGH OUR SITE OR SERVERS BY ANY THIRD PARTY, AND/OR (F) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF YOUR USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA OUR SITE OR ANY SPONSORED ACTIVITY, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT YOU OR BUILDCOMMAND ARE ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.  THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION.<br />
YOU SPECIFICALLY ACKNOWLEDGE THAT BUILDCOMMAND SHALL NOT BE LIABLE FOR CONTENT OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY AND THAT THE RISK OF HARM OR DAMAGE FROM THE FOREGOING RESTS ENTIRELY WITH YOU.<br />
<br />
Our Site is controlled and offered by BuildCommand from its facilities in the United States of America.  BuildCommand makes no representations that our Site or any Sponsored Activity is appropriate or available for use in other locations. Those who access or use our Site or participate in any Sponsored Activity from other jurisdictions do so at their own volition and are responsible for compliance with local law. <br />
<br />
15.	Indemnification.  You agree to indemnify and hold BuildCommand, its subsidiaries, affiliates, licensors, content providers, service providers, employees, agents, officers, directors, and contractors (the “Indemnified Parties”) harmless from any breach of these Terms of Use by you, including any use of content other than as expressly authorized in these Terms of Use.  You agree that the Indemnified Parties shall have no liability in connection with any such breach or unauthorized use, and you agree to indemnify any and all resulting loss, damages, judgments, awards, costs, expenses, and attorney’s fees of the Indemnified Parties in connection therewith.  You also agree to indemnify and hold the Indemnified Parties harmless from and against any claims brought by third parties arising out of your use of the information, Project Proposal and services accessed from our Site.<br />
<br />
16.	Choice of Law, Jurisdiction.  These Terms and Conditions supersede any other agreement between you and BuildCommand to the extent necessary to resolve any inconsistency or ambiguity between them.  Our Site is administered by BuildCommand from its offices in Idaho.  These Terms of Use shall be governed by and construed in accordance with the laws of the State of Idaho, without giving effect to any principles of conflicts of laws.  Any action seeking legal or equitable relief arising out of or relating to our Site shall be brought only in the courts of the State of Idaho or the United States District Court for the District of Idaho.  A printed version of these Terms of Use shall be admissible in judicial and administrative proceedings based upon or relating to these Terms of Use to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. <br />
<br />
17.	Ability to Accept Terms of Use.  You affirm that you are either more than eighteen (18) years of age, or an emancipated minor, or possess legal parental or guardian consent, and are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations, and warranties set forth in these Terms of Use, and to abide by and comply with these Terms of Use. In any case, you affirm that you are over the age of thirteen (13), as our Site and the Sponsored Activities are not intended for children under thirteen (13). If you are under thirteen (13) years of age, then please do not use our Site or engage in any Sponsored Activity.  There are many other great websites for you. Talk to your parents about what sites are appropriate for you.<br />
<br />
18.	Assignment.  These Terms of Use, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by BuildCommand without restriction.<br />
<br />
19.	Termination.  You or we may suspend or terminate your account or your use of our Site at any time, for any reason or for no reason. You are personally liable for any orders that you place or charges that you incur prior to termination. We reserve the right to change, suspend, or discontinue all or any aspect of our Site at any time without notice. <br />
<br />
20.	General.  You agree that the Site and Sponsored Activities shall be deemed solely based in Idaho and that our Site the Sponsored Activities shall not give rise to personal jurisdiction over BuildCommand, either specific or general, in jurisdictions other than Idaho.  These Terms of Use, together with the Privacy Policy and any other legal notices published by BuildCommand on our Site, shall constitute the entire agreement between you and BuildCommand concerning our Site.  If any provision of these Terms of Use is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of these Terms of Use, which shall remain in full force and effect.  No waiver of any term of this these Terms of Use shall be deemed a further or continuing waiver of such term or any other term, and BuildCommand’s failure to assert any right or provision under these Terms of Use shall not constitute a waiver of such right or provision. BuildCommand reserves the right to amend these Terms of Use at any time and without notice, and it is your responsibility to review these Terms of Use for any changes. Your use of the Service following any amendment of these Terms of Use will signify your assent to and acceptance of its revised terms. YOU AND BUILDCOMMAND AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE SERVICES MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.<br />
<br />
Last Update June 1, 2013, Effective June 1, 2013.

</div><?php }} ?>
